apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiaozifs-ui-deployment
  labels:
    apptype: jiaozifs-ui
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: jiaozifs-ui
  template:
    metadata:
      labels:
        app: jiaozifs-ui
        apptype: jiaozifs-ui
    spec:
      containers:
        - name: jiaozifs-ui
          image: gitdatateam/jiaozifs-ui:{{ .Values.tag }}
          imagePullPolicy: Always
          args: [{{ .Values.api_url }}]
          ports:
            - containerPort: 80
