apiVersion: v1
kind: Service
metadata:
  name: jiaozifs-ui-service
  labels:
    apptype: jiaozifs-ui
spec:
  type: ClusterIP
  selector:
    app: jiaozifs-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
