name: test

on:
  create:
    branches:
      if: ${{ startsWith(github.ref, 'refs/heads/deployment/')}}

  push:
    branches:
      - main              # push to main branch
  pull_request:
    branches:
      - '**'              #run check for any pr, and run deployment for deployment branch

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deployment:
    needs:
      - build
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
